name = "my-friendly-pages-site"
compatibility_date = "2025-06-28"

# Build command for Jekyll
[build]
command = "bundle install && bundle exec jekyll build"
upload = { format = "directory", dir = "public" }

# Optional: environment variables
[vars]
JEKYLL_ENV = "production"
